### ISSUE TITLE
When Start the docker eclipse/che and create the java workspace says error with terminal

### ISSUE THREAD

**Issue by tearsakura** [eclipse/che-dockerfiles#32]
When Start the docker eclipse/che and create the java workspace says error with terminal

docker: 1.12
OS: Ubuntu 16.04

Trace:

```
2016-10-28 08:16:31,466[ted-scheduler-0]  [ERROR] [.w.s.WsAgentAnalyticsAddresser 37]   - Failed to send agent analytics
java.net.UnknownHostException: install.codenvycorp.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_45]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_45]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_45]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656) ~[na:1.8.0_45]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_45]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_45]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_45]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_45]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[na:1.8.0_45]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[na:1.8.0_45]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_45]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[na:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_45]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_45]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_45]
	at org.eclipse.che.wsagent.server.WsAgentAnalyticsAddresser.send(WsAgentAnalyticsAddresser.java:35) ~[classes/:4.7.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.eclipse.che.commons.schedule.executor.LoggedRunnable.run(LoggedRunnable.java:53) [che-core-commons-schedule-4.7.2.jar:4.7.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by TylerJewell** [comment]
This output is expected.  We will suppress that exception - it was documented in another issue already.
